[package]
name = "invaria"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Clemens Sonnleitner <@q-wertz>"]
license = "LGPL-3.0-or-later"
description = "Access to (physical) constants."
# homepage = ""  
repository = "https://github.com/q-wertz/invaria"
keywords = ["constant", "canvas", "tree"]
categories = ["scripting", "fun"]
# compiler = "0.13.1" # Should work on any typst version
exclude = ["/data-sources/*", "/tools/*"]
